name: Build

on: push

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Substitute Gradle settings file
        shell: bash
        run: ./substitute-settings.py
        env:
          COMPILER_VERSION: "2.0.0-SNAPSHOT.024"
          VALIDATION_VERSION: "2.0.0-SNAPSHOT.351"
          CORE_JVM_VERSION: "2.0.0-SNAPSHOT.330"
          CORE_JVM_COMPILER_VERSION: "2.0.0-SNAPSHOT.015"

      - name: Build project
        shell: bash
        # For the reason on `--no-daemon` see https://github.com/actions/cache/issues/454
        run: ./gradlew build --stacktrace --no-daemon
